package com.hoyozero.deploy.service;
import com.hoyozero.deploy.entity.Build; import com.hoyozero.deploy.entity.Project; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.context.annotation.Lazy; import java.util.*;
@Service public class RunnerQueueService {
 private final JdbcTemplate jdbc; private final BuildService builds; private final ProjectService projects; private final ReleaseService releaseService;
 public RunnerQueueService(JdbcTemplate j,@Lazy BuildService b,ProjectService p,ReleaseService r){jdbc=j;builds=b;projects=p;releaseService=r;}
 public void enqueue(Long id){jdbc.update("INSERT INTO t_runner_queue(build_id,status,create_time) VALUES(?, 'PENDING', NOW())",id);}
 @Transactional public Map<String,Object> claim(String runner)throws InterruptedException{List<Long> ids=jdbc.query("SELECT build_id FROM t_runner_queue WHERE status='PENDING' ORDER BY id LIMIT 1 FOR UPDATE",(rs,n)->rs.getLong(1));if(ids.isEmpty()){Thread.sleep(1000);return null;}Long id=ids.get(0);jdbc.update("UPDATE t_runner_queue SET status='RUNNING',runner_name=?,claim_time=NOW() WHERE build_id=?",runner,id);Build b=builds.getById(id);Project p=b==null?null:projects.getById(b.getProjectId());if(b==null||p==null)return null;b.setStatus("RUNNING");b.setStage("runner执行");b.setRunnerName(runner);b.setStartTime(java.time.LocalDateTime.now());builds.updateById(b);Map<String,Object> m=new HashMap<>();m.put("buildId",id);m.put("projectId",p.getId());m.put("gitUrl",p.getGitUrl());m.put("branch",p.getBranch());m.put("gitUsername",Objects.toString(p.getGitUsername(),""));m.put("gitToken",Objects.toString(p.getGitPassword(),""));m.put("dockerfilePath",Objects.toString(p.getDockerfilePath(),"Dockerfile"));m.put("dockerContext",Objects.toString(p.getDockerContext(),"."));m.put("registryUrl",Objects.toString(p.getRegistryUrl(),""));m.put("registryUsername",Objects.toString(p.getRegistryUsername(),""));m.put("registryToken",Objects.toString(p.getRegistryToken(),""));m.put("registryNamespace",Objects.toString(p.getRegistryNamespace(),""));m.put("imageName",p.getImageName());m.put("env",Objects.toString(p.getEnv(),"dev"));m.put("platform",Objects.toString(p.getBuildPlatform(),"linux/amd64"));return m;}
 public void result(Long id,String status,String log,String commit,String image,String tag,String digest,String reason){jdbc.update("UPDATE t_runner_queue SET status=?,finish_time=NOW() WHERE build_id=?",status,id);Build b=builds.getById(id);if(b==null)return;b.setStatus(status);b.setLog(log);b.setGitCommit(commit);b.setImage(image);b.setImageTag(tag);b.setImageDigest(digest);b.setFailureReason(reason);b.setStage(status.equals("SUCCESS")?"完成":"失败");b.setEndTime(java.time.LocalDateTime.now());if(b.getStartTime()!=null)b.setDuration(java.time.Duration.between(b.getStartTime(),b.getEndTime()).getSeconds());builds.updateById(b);releaseService.onBuildFinished(id,status,reason,image);}
}
